deployments:
- build_id: 0c3d9902-ec2b-4e06-96ac-bf9c097c5a35
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-19T12:02:41.861460'
  deployment_id: f7b05d25-e5b7-4a6f-84dc-4f1571f81f66
  image: jhnnsrs/kare:0.0.1
  manifest:
    author: jhnnsrs
    created_at: '2023-09-19T12:00:01.863371'
    entrypoint: app
    identifier: kare
    requirements: []
    scopes:
    - read
    version: 0.0.1
- build_id: eaafa991-d424-4b9b-b06a-7ae2d48a3eb1
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-19T13:16:05.125226'
  deployment_id: 16c549d4-362a-40ca-8c35-e053cc2e62e6
  image: jhnnsrs/kare:0.0.2
  manifest:
    author: jhnnsrs
    created_at: '2023-09-19T13:15:54.955237'
    entrypoint: app
    identifier: kare
    requirements:
    - gpu
    scopes:
    - read
    version: 0.0.2
- build_id: 34f2e88b-222f-4213-9f10-6c7396397cc0
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-21T15:31:48.512895'
  deployment_id: 4176effe-081c-4e75-bf4e-3c6c4ab6a936
  image: jhnnsrs/kare:0.0.3
  manifest:
    author: jhnnsrs
    created_at: '2023-09-21T15:31:34.818972'
    entrypoint: app
    identifier: kare
    requirements:
    - gpu
    scopes:
    - read
    version: 0.0.3
latest_deployment: '2023-09-21T15:31:48.515142'
