deployments:
- builder: arkitekt.builder.port
  definitions: []
  deployed:
    docker: jhnnsrs/kare:6
    runtime: standard
  deployer: arkitekt.deployers.port.dockerbuild
  identifier: kare
  scopes:
  - read
  version: '6'
