deployments:
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-12T17:47:27.624024'
  definitions: []
  entrypoint: app
  identifier: kare
  image: jhnnsrs/kare:dev
  requirements:
  - gpu
  scopes:
  - read
  version: dev
